[package]
name = "modeling-ops"
version = "0.1.0"
edition = "2021"

[dependencies]
kernel-fork = { path = "../kernel-fork" }
waffle-types = { path = "../waffle-types" }
uuid = { version = "1", features = ["v4", "serde"] }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
